local opts = { noremap = true, silent = true }
local map = vim.api.nvim_set_keymap

map("n", "<C-Q>", "<esc><cmd>q!<cr>", opts)
map("n", "<C-s>", "<cmd>w<cr>", opts)
map("n", "<A-S-s>", "<cmd>TokyoVimSaveSession<cr>", opts)
map("n", "<A-S-l>", "<cmd>TokyoVimLoadSession<cr>", opts)
map("n", "<A-j>", "<cmd>m .+1<cr>==", opts)
map("n", "<A-k>", "<cmd>m .-2<cr>==", opts)
map("n", "<A-n>", "<cmd>vsplit<cr>", opts)
map("n", "<A-b>", "<cmd>split<cr>", opts)
map("n", "<C-h>", "<C-w>h", opts)
map("n", "<C-l>", "<C-w>l", opts)
map("n", "<C-k>", "<C-w>k", opts)
map("n", "<C-j>", "<C-w>j", opts)
map("n", "<C-z>", "u", opts)
map("n", "<C-v>", "p<esc>", opts)
map("n", "<C-a>", "ggVG", opts)
map("n", "<C-A-h>", "<cmd>vertical resize +3<cr>", opts)
map("n", "<C-A-l>", "<cmd>vertical resize -3<cr>", opts)
map("n", "<C-A-j>", "<cmd>resize -3<cr>", opts)
map("n", "<C-A-k>", "<cmd>resize +3<cr>", opts)
map("n", "<S-j>", "yyp", opts)
map("n", "<leader>F", "<cmd>TokyoVimFormat<cr>", opts)
map("n", "<esc>", "<cmd>noh<return><esc>", opts)

map("v", "<C-Q>", "<esc><cmd>q!<cr>", opts)
map("v", "<C-z>", "<esc>u<esc>gv=gv", opts)
map("v", "<C-c>", "y<esc>", opts)
map("v", "<C-v>", "p<esc>gv=gv", opts)
map("v", "<C-a>", "ggVG", opts)
map("v", "<A-j>", "<cmd>m '>+1<cr>gv-gv", opts)
map("v", "<A-k>", "<cmd>m '<-2<cr>gv-gv", opts)
map("v", "<", "<gv", opts)
map("v", ">", ">gv", opts)

map("i", "<C-Q>", "<esc><cmd>q!<cr>", opts)
map("i", "<C-h>", "<Left>", opts)
map("i", "<C-j>", "<Down>", opts)
map("i", "<C-k>", "<Up>", opts)
map("i", "<C-l>", "<Right>", opts)

map("t", "<A-h>", "<cmd>ToggleTerm<cr>", opts)
map("t", "<A-m>", "<cmd>ToggleTerm<cr>", opts)
map("t", "<A-i>", "<cmd>ToggleTerm<cr>", opts)

map("x", "<F4>", "<cmd>lua vim.lsp.buf.range_code_action()<cr>", opts)
